apiVersion: argoproj.io/v1alpha1
kind: AppProject   
metadata:
  name: cluster_env
spec:      
  sourceNamespaces:
  - 'cluster_env'                  
  clusterResourceBlacklist:
  - group: '*'
    kind: '*'   
  namespaceResourceBlacklist:
  - group: '*'
    kind: 'Namespace'  
  - group: '*'
    kind: 'CustomResourceDefinition'
  destinations:
  - name: '*'
    namespace: 'cluster_env'
    server: '*'
  - name: '*'
    namespace: 'glueops-core'
    server: '*'
  roles:
  - description: example-tenant:developers
    groups:
    - "example-tenant:developers"
    policies:
    - p, proj:cluster_env:read-only, applications, get, cluster_env/*, allow  
    name: read-only
  sourceRepos:
  - https://helm.gpkg.io/project-template
  - https://helm.gpkg.io/service
  - https://incubating-helm.gpkg.io/project-template
  - https://incubating-helm.gpkg.io/service
  - https://incubating-helm.gpkg.io/platform
  - https://github.com/example-tenant/*