apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster_env-application-set
  namespace: glueops-core
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: https://github.com/example-tenant/deployment-configurations
      revision: HEAD
      directories:
      - path: 'apps/*/envs/*'
      - path: 'apps/*/envs/previews'
        exclude: true
  template:
    metadata:
      name: '{{ index .path.segments 1 | replace "." "-"  | replace "_" "-" }}-{{ .path.basenameNormalized }}'
      namespace: cluster_env
      annotations:
        preview_environment: 'false'
    spec:
      destination:
        namespace: cluster_env
        server: https://kubernetes.default.svc
      project: cluster_env
      sources:
      - chart: app
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
          - '$values/common/common-values.yaml'
        # prod
        #   - '$values/env-overlays/prod/env-values.yaml'
        # nonprod
        #   - '$values/env-overlays/nonprod/env-values.yaml'
          - '$values/apps/{{ index .path.segments 1 }}/base/base-values.yaml'
          - '$values/{{ .path.path }}/values.yaml'
          values: |-
            captain_domain: CLUSTER_VARIABLE
            appName: '{{ index .path.segments 1 | replace "." "-"  | replace "_" "-" }}-{{ .path.basenameNormalized }}'

        repoURL: https://helm.gpkg.io/project-template
        targetRevision: 0.6.0
      - repoURL: https://github.com/example-tenant/deployment-configurations
        targetRevision: main
        ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 2
        syncOptions:
        - CreateNamespace=true
