apiVersion: v1
kind: Secret
metadata:
  name: aws-ecr-credentials
  namespace: cluster_env
stringData:
  access-key-id: "key_id"
  secret-access-key: "key_value"
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: ecr-generator
  namespace: cluster_env
spec:
  region: us-west-2
  auth:
    secretRef:
      accessKeyIDSecretRef:
        name: "aws-ecr-credentials"
        key: "access-key-id"
      secretAccessKeySecretRef:
        name: "aws-ecr-credentials"
        key: "secret-access-key"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ecr-regcred
  namespace: cluster_env
spec:
  refreshInterval: "10h"
  target:
    name: ecr-regcred
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .proxy_endpoint }}": {
                "auth": "{{ printf "%s%s" "AWS:" .password | b64enc }}"
              }
            }
          }
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ECRAuthorizationToken
        name: ecr-generator