apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pull-request-preview-environments
  namespace: glueops-core
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
      - scmProvider:
          cloneProtocol: https
          github:
            allBranches: false
            organization: example-tenant
            appSecretName: tenant-repo-creds
          filters:
            - repositoryMatch: wordpress.*
            
      - pullRequest:
          github:
            owner: example-tenant
            appSecretName: tenant-repo-creds
            repo: '{{ .repository }}'
          requeueAfterSeconds: 30
  template:
    metadata:
      name: '{{ .branch_slug }}-{{ .repository | replace "." "-"  | replace "_" "-" }}'
      namespace: cluster_env
      annotations:
        repository_organization: "example-tenant"
        repository_name: '{{ .repository }}'
        preview_environment: 'true'
        pull_request_number: '{{.number}}'
        branch: '{{.branch}}'
        branch_slug: '{{.branch_slug}}'
        head_sha: '{{.head_sha}}'
        head_short_sha: '{{.head_short_sha}}'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      labels:
        type: pull-request
    spec:
      sources:
        - repoURL: https://helm.gpkg.io/project-template
          chart: app
          targetRevision: 0.6.0
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
            - '$configValues/common/common-values.yaml'
            - '$configValues/env-overlays/cluster_env/env-values.yaml'
            - '$configValues/apps/{{ .repository }}/base/base-values.yaml'
            - '$configValues/apps/{{ .repository }}/envs/previews/common/values.yaml'
            - '$configValues/apps/{{ .repository }}/envs/previews/pull-request-number/{{ .number }}/values.yaml'
            values: |-
              appName: '{{ .branch_slug }}-{{ .repository | replace "." "-"  | replace "_" "-" }}'
              image:
                tag: '{{.head_sha}}'

              ingress:
                enabled: true
                ingressClassName: public
                entries:
                  - name: public
                    hosts:
                    - hostname: '{{ .head_short_sha }}-{{ .repository | replace "." "-"  | replace "_" "-" }}.apps.CLUSTER_VARIABLE'

        - repoURL: https://github.com/example-tenant/{{ .repository }}
          targetRevision: '{{ .head_sha }}'
          ref: values
        - repoURL: https://github.com/example-tenant/deployment-configurations
          targetRevision: main
          ref: configValues
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 2
        syncOptions:
        - CreateNamespace=true

      project: cluster_env
      destination:
        server: https://kubernetes.default.svc
        namespace: cluster_env
