apiVersion: metacontroller.glueops.dev/v1alpha1
kind: WebApplicationFirewallWebACL
metadata:
  name: rate-limit-only
spec:
  web_acl_definition: |
    {
        "DefaultAction": {
            "Allow": {}
        },
        "Description": "Provided by GlueOps",
        "Rules": [
            {
                "Name": "too-many-requests-per-source-ip",
                "Priority": 3,
                "Statement": {
                    "RateBasedStatement": {
                        "Limit": 100,
                        "AggregateKeyType": "IP"
                    }
                },
                "Action": {
                    "Block": {
                        "CustomResponse": {
                            "ResponseCode": 429,
                            "CustomResponseBodyKey": "http_429_response"
                        }
                    }
                },
                "VisibilityConfig": {
                    "SampledRequestsEnabled": true,
                    "CloudWatchMetricsEnabled": true,
                    "MetricName": "too-many-requests-per-source-ip"
                }
            }
        ],
        "VisibilityConfig": {
            "SampledRequestsEnabled": true,
            "CloudWatchMetricsEnabled": true,
            "MetricName": "primary"
        },
        "Capacity": 2,


        "CustomResponseBodies": {
            "http_429_response": {
                "ContentType": "APPLICATION_JSON",
                "Content": "{\nerror: \"HTTP 429 Too Many Requests.\"\n}\n"
            }
        }
    }
---
apiVersion: metacontroller.glueops.dev/v1alpha1
kind: WebApplicationFirewallWebACL
metadata:
  name: primary
spec:
  web_acl_definition: |
    {
            "DefaultAction": {
                "Allow": {}
            },
            "Description": "Provided by GlueOps",
            "Rules": [
                {
                    "Name": "AWS-AWSManagedRulesAmazonIpReputationList",
                    "Priority": 1,
                    "Statement": {
                        "ManagedRuleGroupStatement": {
                            "VendorName": "AWS",
                            "Name": "AWSManagedRulesAmazonIpReputationList"
                        }
                    },
                    "OverrideAction": {
                        "None": {}
                    },
                    "VisibilityConfig": {
                        "SampledRequestsEnabled": true,
                        "CloudWatchMetricsEnabled": true,
                        "MetricName": "AWS-AWSManagedRulesAmazonIpReputationList"
                    }
                },
                {
                    "Name": "AWS-AWSManagedRulesAnonymousIpList",
                    "Priority": 2,
                    "Statement": {
                        "ManagedRuleGroupStatement": {
                            "VendorName": "AWS",
                            "Name": "AWSManagedRulesAnonymousIpList"
                        }
                    },
                    "OverrideAction": {
                        "None": {}
                    },
                    "VisibilityConfig": {
                        "SampledRequestsEnabled": true,
                        "CloudWatchMetricsEnabled": true,
                        "MetricName": "AWS-AWSManagedRulesAnonymousIpList"
                    }
                },
                {
                    "Name": "too-many-requests-per-source-ip",
                    "Priority": 3,
                    "Statement": {
                        "RateBasedStatement": {
                            "Limit": 100,
                            "AggregateKeyType": "IP"
                        }
                    },
                    "Action": {
                        "Block": {
                            "CustomResponse": {
                                "ResponseCode": 429,
                                "CustomResponseBodyKey": "http_429_response"
                            }
                        }
                    },
                    "VisibilityConfig": {
                        "SampledRequestsEnabled": true,
                        "CloudWatchMetricsEnabled": true,
                        "MetricName": "too-many-requests-per-source-ip"
                    }
                },
                {
                    "Name": "AWS-AWSManagedRulesWordPressRuleSet",
                    "Priority": 4,
                    "Statement": {
                        "ManagedRuleGroupStatement": {
                            "VendorName": "AWS",
                            "Name": "AWSManagedRulesWordPressRuleSet",
                            "Version": "Version_1.1"
                        }
                    },
                    "OverrideAction": {
                        "None": {}
                    },
                    "VisibilityConfig": {
                        "SampledRequestsEnabled": true,
                        "CloudWatchMetricsEnabled": true,
                        "MetricName": "AWS-AWSManagedRulesWordPressRuleSet"
                    }
                }
            ],
            "VisibilityConfig": {
                "SampledRequestsEnabled": true,
                "CloudWatchMetricsEnabled": true,
                "MetricName": "primary"
            },
            "CustomResponseBodies": {
                "http_429_response": {
                    "ContentType": "APPLICATION_JSON",
                    "Content": "{\nerror: \"HTTP 429 Too Many Requests.\"\n}\n"
                }
            }
    }
---
apiVersion: metacontroller.glueops.dev/v1alpha1
kind: WebApplicationFirewallWebACL
metadata:
  name: block-bad-networks
spec:
  web_acl_definition: |
    {
        "DefaultAction": {
            "Allow": {}
        },
        "Description": "Provided by GlueOps",
        "Rules": [
            {
                "Name": "AWS-AWSManagedRulesAmazonIpReputationList",
                "Priority": 1,
                "Statement": {
                    "ManagedRuleGroupStatement": {
                        "VendorName": "AWS",
                        "Name": "AWSManagedRulesAmazonIpReputationList"
                    }
                },
                "OverrideAction": {
                    "None": {}
                },
                "VisibilityConfig": {
                    "SampledRequestsEnabled": true,
                    "CloudWatchMetricsEnabled": true,
                    "MetricName": "AWS-AWSManagedRulesAmazonIpReputationList"
                }
            },
            {
                "Name": "AWS-AWSManagedRulesAnonymousIpList",
                "Priority": 2,
                "Statement": {
                    "ManagedRuleGroupStatement": {
                        "VendorName": "AWS",
                        "Name": "AWSManagedRulesAnonymousIpList"
                    }
                },
                "OverrideAction": {
                    "None": {}
                },
                "VisibilityConfig": {
                    "SampledRequestsEnabled": true,
                    "CloudWatchMetricsEnabled": true,
                    "MetricName": "AWS-AWSManagedRulesAnonymousIpList"
                }
            }
        ],
        "VisibilityConfig": {
            "SampledRequestsEnabled": true,
            "CloudWatchMetricsEnabled": true,
            "MetricName": "primary"
        },
        "CustomResponseBodies": {
            "http_429_response": {
                "ContentType": "APPLICATION_JSON",
                "Content": "{\nerror: \"HTTP 429 Too Many Requests.\"\n}\n"
            }
        }
    }
---
apiVersion: metacontroller.glueops.dev/v1alpha1
kind: WebApplicationFirewallWebACL
metadata:
  name: block-bad-networks-and-rate-limit
spec:
  web_acl_definition: |
    {
        "DefaultAction": {
            "Allow": {}
        },
        "Description": "Provided by GlueOps",
        "Rules": [
            {
                "Name": "AWS-AWSManagedRulesAmazonIpReputationList",
                "Priority": 1,
                "Statement": {
                    "ManagedRuleGroupStatement": {
                        "VendorName": "AWS",
                        "Name": "AWSManagedRulesAmazonIpReputationList"
                    }
                },
                "OverrideAction": {
                    "None": {}
                },
                "VisibilityConfig": {
                    "SampledRequestsEnabled": true,
                    "CloudWatchMetricsEnabled": true,
                    "MetricName": "AWS-AWSManagedRulesAmazonIpReputationList"
                }
            },
            {
                "Name": "AWS-AWSManagedRulesAnonymousIpList",
                "Priority": 2,
                "Statement": {
                    "ManagedRuleGroupStatement": {
                        "VendorName": "AWS",
                        "Name": "AWSManagedRulesAnonymousIpList"
                    }
                },
                "OverrideAction": {
                    "None": {}
                },
                "VisibilityConfig": {
                    "SampledRequestsEnabled": true,
                    "CloudWatchMetricsEnabled": true,
                    "MetricName": "AWS-AWSManagedRulesAnonymousIpList"
                }
            },
            {
                "Name": "too-many-requests-per-source-ip",
                "Priority": 3,
                "Statement": {
                    "RateBasedStatement": {
                        "Limit": 100,
                        "AggregateKeyType": "IP"
                    }
                },
                "Action": {
                    "Block": {
                        "CustomResponse": {
                            "ResponseCode": 429,
                            "CustomResponseBodyKey": "http_429_response"
                        }
                    }
                },
                "VisibilityConfig": {
                    "SampledRequestsEnabled": true,
                    "CloudWatchMetricsEnabled": true,
                    "MetricName": "too-many-requests-per-source-ip"
                }
            }
        ],
        "VisibilityConfig": {
            "SampledRequestsEnabled": true,
            "CloudWatchMetricsEnabled": true,
            "MetricName": "primary"
        },
        "CustomResponseBodies": {
            "http_429_response": {
                "ContentType": "APPLICATION_JSON",
                "Content": "{\nerror: \"HTTP 429 Too Many Requests.\"\n}\n"
            }
        }
    }